# Generated by Django 4.2.4 on 2023-08-23 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0002_reservation_created_at_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
