version: "1.0" # opsiyonel

services:

    frontend:
        # container_name: "anotherName" # Container farklı isim ver.
        image: "docker-compose-frontend"
        build: ./frontend
        ports:
            - 3000:3000
            - 80:3000
        restart: on-failure
        depends_on: # önce aşağıdaki servisi çalıştır.
            - backend

    backend:
        # Varsa kullan, yoksa build et:
        image: "docker-compose-backend"
        # Proje klasörü:
        build: ./backend
        # Portlar:
        ports: 
            - 8000:8000 # Dış Port : İç Port
        restart: on-failure # Hata durunda stop/start yap.
        volumes: # fiziksel yollar (external:internal) 
            - $PWD/backend/db.sqlite3:/backend/db.sqlite3
