# Generated by Django 4.2.4 on 2023-08-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog ', 'verbose_name_plural': 'Blogs '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog category', 'verbose_name_plural': 'Blog categories'},
        ),
    ]
