# Generated by Django 4.2.5 on 2023-09-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='products',
            new_name='product',
        ),
    ]
