# Generated by Django 4.2.4 on 2023-08-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='personnel.department'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='title',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Team Lead'), (3, 'Developer'), (4, 'Junior')]),
        ),
    ]
